image_processing:
  cameras:
    - index: 2
      type: "fisheye"
      crop_region:
        x: 0
        y: 50
        width: 100
        height: 100

    # - index: 1
    #   type: normal
    #   crop_regions:
    #     - x: 0
    #       y: 100
    #       width: 400
    #       height: 300
    # - index: 2
    #   type: normal
